import {ChallengeEntry as CE} from "./challenge-entry.js";

export const challenges = {
    'economics': [
        new CE("Delete 1 starting vill", 2),
        new CE("Delete 2 starting vills", 4),
        new CE("Delete 3 starting vills", 7),
        new CE("No sheep", 3, null, "no_sheep"),
        new CE("No hunt", 2),
        new CE("No forage bush", 1),
        new CE("No mining camps", 3, null, "no_mining_camps"),
        new CE("No lumber camps", 4, null, "no_lumber_camps"),
        new CE("No mills (except for 1)", 2, null, "no_mills"),
        new CE("No extra TCs", 3),
        new CE("Kill n% vills per age", 3, ['10', '20', '30', '40', '50']),
        new CE("Max 22-n vills in dark age", 4, [-4, -8]),
        new CE("No mining camp upgrades", 2, null, "no_mining_camp_upgrades"),
        new CE("No lumber camp upgrades", 2, null, "no_lumber_camp_upgrades"),
        new CE("No mill upgrades", 1, null, "no_mill_upgrades"),
        new CE("No stone", 2, null, "no_stone"),
        new CE("No gold", 3, null, "no_gold"),
        new CE("No selling/buying", 3, null, "no_selling_buying"),
        new CE("No trade", 1, null, "no_trade"),
        new CE("Send sheep to solo player", 4, null, "send_sheep_to_solo"),
        new CE("No wheelbarrow", 2),
        new CE("No loom", 5),
    ],
    'military': [
        new CE("No gold units (except siege)", 9, null, "no_gold_units"),
        new CE("No trash units", 5, null, "no_trash"),
        new CE("No unique unit", 2, null, "no_uu"),
        new CE("Delete starting scout", 3),
        new CE("One unit type per mil. building", 3),
        new CE("Only make 1 unit type in Feudal", 3),
        new CE("No eagles", 1, null, "no_eagles"),
        new CE("No elephants", 1, null, "no_elephants"),
        new CE("No knight line", 3, null, "no_knights"),
        new CE("No archer line", 3, null, "no_archers"),
        new CE("No cav-archers", 1, null, "no_cav_archers"),
    ],
    'building': [
        new CE("Every building twice", 10),
        new CE("No walls", 4, null, "no_walls"),
        new CE("Leave gaps between walls", 5),
        new CE("No towers (donjon)", 3),
        new CE("No barracks", 4, null, "no_barracks"),
        new CE("No archery range", 6, null, "no_archery_range"),
        new CE("No stable", 6, null, "no_stable"),
        new CE("No university", 3, null, "no_university"),
        new CE("No monastery", 2, null, "no_monastery"),
        new CE("No castles (krepost)", 7, null, "no_castle"),
        new CE("No siege workshop", 4),
        new CE("No docks", 3),
        new CE("No market", 6, null, "no_market"),
        new CE("Instant 8 houses", 3, null, "instant_8_houses"),
        new CE("Instant barracks", 2, null, "instant_barracks"),
        new CE("Make all possible buildings", 4),
        new CE("All military buildings in one camp", 4),
    ],
    'technologies': [
        new CE("One age behind blacksmith upgrades", 5),
        new CE("No archer range & attack", 5, null, "no_archer_attack"),
        new CE("No archer defence", 3, null, "no_archer_defence"),
        new CE("No melee attack", 2, null, "no_melee_attack"),
        new CE("No infantry defence", 2, null, "no_infantry_defence"),
        new CE("No cavalry defence", 4, null, "no_cavalry_defence"),
        new CE("No unique techs", 1, null, "no_unique_techs"),
        new CE("No bloodlines", 1, null, "no_bloodlines"),
        new CE("No ballistics", 2, null, "no_ballistics"),
        new CE("Get murder holes", 1, null, "get_murder_holes"),
        new CE("Get heresy", 3, null, "get_heresy"),
    ],
    'commands': [
        new CE("Delete all forwards", 8),
        new CE("Delete all houses", 2),
        new CE("Send all of resource x", 4, null, "send_all_x_resource"),
        new CE("Delete all TCs (Feudal+)", 7, null, "delete_all_tcs"),
        new CE("Cancel all queues", 2),
        new CE("Delete all walls", 2, null, "delete_all_walls"),
        new CE("Create gap in wall at X", 1),
        new CE("Send all army to X", 3),
        new CE("Sell all of resource x", 1, null, "sell_all_x_resource"),
        new CE("All players delete all military", 4),
        new CE("Use 1 monk to deliver a relic", 1, null, "deliver_relic"),
    ],
    'miscellaneous': [
        new CE("[Solo] Choose civ for points", 2),
        new CE("[Solo] Allow laming", 2),
        new CE("No laming", 1),
        new CE("Max 150 pop", 2, null, "max_150_pop"),
        new CE("Max 100 pop", 4, null, "max_100_pop"),
        new CE("Max 75 pop", 7, null, "max_75_pop"),
        new CE("No scouting (except vills)", 4),
        new CE("One player migrates to ally", 9, null, "ally_migration"),
        new CE("No relics", 1),
        new CE("Instant loom", 1),
        new CE("Sacrifice 10 monks", 4),
        new CE("Kill 5 vills each time housed", 5),
    ],
}

export const mutuallyExclusive = [
    ['no_stone', 'no_gold', 'no_selling_buying'],
    ['no_barracks', 'no_archery_range', 'no_stable', 'no_gold_units', 'no_trash'],
    ['no_sheep', 'send_sheep_to_solo'],
    ['max_150_pop', 'max_100_pop', 'max_75_pop'],
    ['no_barracks', 'instant_barracks'],
    ['instant_8_houses', 'instant_barracks', 'ally_migration'],
    ['no_archer_attack', 'no_archer_defence'],
    ['no_infantry_defence', 'no_melee_attack'],
    ['no_melee_attack', 'no_cavalry_defence'],
    ['no_lumber_camps', 'delete_all_tcs'],
    ['no_mining_camps', 'delete_all_tcs'],
    ['no_trash', 'no_gold']
]

export const oneWayExclusive = {
    'no_walls': ['delete_all_walls'],
    'no_selling_buying': ['sell_all_x_resource'],
    'no_castle': ['no_uu', 'no_unique_techs'],
    'no_mining_camps': ['no_mining_camp_upgrades'],
    'no_lumber_camps': ['no_lumber_camp_upgrades'],
    'no_mills': ['no_mill_upgrades'],
    'no_market': ['no_stone', 'no_gold', 'no_selling_buying', 'sell_all_x_resource', 'no_trade', 'send_all_x_resource'],
    'no_stable': ['no_bloodlines', 'no_elephants', 'no_knights'],
    'no_barracks': ['no_eagles'],
    'no_archery_range': ['no_archers', 'no_cav_archers'],
    'no_university': ['no_ballistics', 'get_murder_holes'],
    'no_monastery': ['get_heresy', 'deliver_relic']
}

export const allButOne = [
    // Todo: Add this
]